### PR TITLE
fix: solve bug with animations

### LINKED ISSUE #54: Fix the animation bug of the bottom navigation bar
- There is an animation bug especially for the transition from the research to the dashboard and from the dashboard to the profile. Here's a video of the bug. It has to be fixed before Friday.
https://github.com/user-attachments/assets/0ab36c13-0e2f-4a28-bebc-e70434063c6e

### PR DESCRIPTION
**Pull request by AnotherMedo**
Added the following:
- Fix to a faulty animation in the bottom navigation bar
- Refinements on the pre-existing animations to make them more visible
- refactor bottom navigation bar location in code to decrease code duplication

closes #54

### CODE REVIEW

**Review by daferya — APPROVED** [review]
Well done! Your work is accurate and well-executed. You could use a list or a set of Screen values to simplify the logic and make it more readable.

File: app/src/main/java/com/arygm/quickfix/MainActivity.kt [hunk 1]
```diff
@@ -45,58 +60,111 @@ class MainActivity : ComponentActivity() {
...
-    ) {
-      composable(Screen.ACTIVITY) { ActivityScreen(navigationActions, isUser) }
+  val screen by remember { navigationActions::currentScreen }
+  // Make `bottomBarVisible` reactive to changes in `screen`
+  val shouldShowBottomBar by remember {
+    derivedStateOf {
+      screen != Screen.WELCOME &&
+          screen != Screen.LOGIN &&
+          screen != Screen.INFO &&
+          screen != Screen.PASSWORD
```
[the remark this answers is not in the document]
Comment (AnotherMedo) [reply app/src/main/java/com/arygm/quickfix/MainActivity.kt:75]: This will be done further on in the project life when all screens are implemented

File: app/src/androidTest/java/com/arygm/quickfix/MainActivityTest.kt [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    composeTestRule.onNodeWithTag("logInButton").performClick()
+    composeTestRule.mainClock.advanceTimeBy(1000L)
+    // enter email
+    composeTestRule.onNodeWithTag("inputEmail").performTextInput(testEmail)
+
+    // enter password
+    composeTestRule.onNodeWithTag("inputPassword").performTextInput(testPassword)
+
+    // click on log in
+    composeTestRule.onNodeWithTag("logInButton").performClick()
```
Comment (Sebbayra) [inline app/src/androidTest/java/com/arygm/quickfix/MainActivityTest.kt:37]: As we have too many test tags to keep track of, we can maybe use:
[Semantic Matchers](https://developer.android.com/develop/ui/compose/accessibility/semantics?hl=fr)

File: app/src/androidTest/java/com/arygm/quickfix/ui/authentication/InfoScreenTest.kt [hunk 3]
```diff
@@ -121,6 +121,9 @@ class InfoScreenTest {
 
     // Click the button and verify navigation
     composeTestRule.onNodeWithTag("nextButton").performClick()
+
+    composeTestRule.mainClock.advanceTimeBy(500L)
+
```
Comment (Sebbayra) [inline app/src/androidTest/java/com/arygm/quickfix/ui/authentication/InfoScreenTest.kt:126]: You can maybe use the wait function with the condition of the navigation action invocations being empty, but with a reasonable waiting time.

File: app/src/androidTest/java/com/arygm/quickfix/ui/authentication/InfoScreenTest.kt [hunk 4]
```diff
@@ -148,6 +151,8 @@ class InfoScreenTest {
     // Click the back button
     composeTestRule.onNodeWithTag("goBackButton").performClick()
 
+    // perform delay here 500ms
+    composeTestRule.mainClock.advanceTimeBy(500L)
```
Comment (Sebbayra) [inline app/src/androidTest/java/com/arygm/quickfix/ui/authentication/InfoScreenTest.kt:155]: Same comment as before, but it comes down to personal preference.

File: app/src/main/java/com/arygm/quickfix/MainActivity.kt
Comment (Sebbayra) [inline app/src/main/java/com/arygm/quickfix/MainActivity.kt:1]: I think, this is a great idea to avoid duplicating code, like initializing the bottom bar on each screen which caused the animation bug, so love it.

**Review by Sebbayra — APPROVED** [review]

File: app/src/androidTest/java/com/arygm/quickfix/MainActivityTest.kt (hunk 2 above)
Comment (AnotherMedo) [reply app/src/androidTest/java/com/arygm/quickfix/MainActivityTest.kt:37]: Will research it for future PRs! (maybe another refactoring PR in the works? 👀)
