### PR TITLE
Link Search Engine and Fix UI Bugs

### LINKED ISSUE #286: Link Search Engine and Fix UI Bugs

### PR DESCRIPTION
**Pull request by Sebbayra**
Not much to say, just fixed the UI layout and linked the search engine.

### CODE REVIEW

File: app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerProfileResult.kt [hunk 1]
```diff
@@ -50,10 +52,22 @@ fun SearchWorkerProfileResult(
...
+        name
+      } else {
+        name.take(25) + "..."
+      }
+  val displayCateg =
+      if (category.length <= 21) {
+        category
+      } else {
+        category.take(21) + "..."
       }
```
Comment (mohagpt) [inline app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerProfileResult.kt:71]: It might be better to create some constants here explaining the choice of these particular values.

**Review by mohagpt — COMMENTED** [review]
Great job integrating the backend search engine connection. Given our deadline, establishing that functionality was critical for completing the application on time. The code looks solid and addresses the requirements effectively. Add tests to bring the new code coverage to at least 80% before merging to ensure code reliability and meet our quality standards.

**Review by mohagpt — APPROVED** [review]
The line coverage is now over 80%, meeting the required threshold. This can be merged into main.
